### ISSUE TITLE
add the histogram in sidenav.html

### ISSUE THREAD

**Issue by wasim7raja10** [wasim7raja10/Codeforces-tracker#10]
![Screenshot from 2021-10-02 14-09-11](https://user-images.githubusercontent.com/42181953/135709538-c451db04-45ec-4c3f-88d0-dbe4c79bebb7.png)

1. Use bootstrap appropriate components if necessary to make it responsive. Both cards should be aligned vertically on mobile.
2. Use appropriate HTML tags and attributes if required so that the data can be updated.
3. Use Google chart for the histogram chart (read [CONTRIBUTING.md](https://github.com/wasim7raja10/Codeforces-tracker/blob/main/CONTRIBUTING.md) )
4. refer to [drive](https://drive.google.com/file/d/1UtiWpcFj6Ij_147YWT3duR8FXmY85VYY/view?usp=drivesdk) for the whole UI

**Comment by harshitsuthar77731** [comment]
please assign me i want to do this

**Comment by harshitsuthar77731** [comment]
i want to learn new skill of frontend

**Comment by wasim7raja10** [comment]
@harshitsuthar77731 sure, go ahead. Update your loc repo with current state, you can check out the code for pie chart contributed by @JigmeT123 and try to implement in similar way. You'll learn in this way. Refer to google chart for more info.
