### ISSUE TITLE
Add Stats and Problems card on the sidenav.html

### ISSUE THREAD

**Issue by wasim7raja10** [wasim7raja10/Codeforces-tracker#11]
![Screenshot from 2021-10-02 14-42-59](https://user-images.githubusercontent.com/42181953/135710348-8ccbac96-2acf-4145-8282-8a813a24b961.png)

1. Use bootstrap appropriate components if necessary to make it responsive.
2. Use appropriate HTML tags and attributes so that the data can be updated.
3. on the left-hand side of the card you can see two tabs, both tabs have exactly the same data headings like "Tried" "Solved" but data will be different. So, clicking on the other tab should show the new data.
4. refer to [drive](https://drive.google.com/file/d/1UtiWpcFj6Ij_147YWT3duR8FXmY85VYY/view?usp=drivesdk) for the whole UI

**Comment by ganaaduvva** [comment]
I like to work on the issue @wasim7raja10  kindly assign me .

**Comment by wasim7raja10** [comment]
> I like to work on the issue @wasim7raja10  kindly assign me .

You are assigned. Please follow the git workflow guide given in the readme. If you have any doubt, feel free to ask us.

**Comment by ganaaduvva** [comment]
Absolutely, Thank you for your approval!!
