### ISSUE TITLE
add footer in sidenav.html

### ISSUE THREAD

**Issue by wasim7raja10** [wasim7raja10/Codeforces-tracker#13]
![Screenshot from 2021-10-02 14-50-12](https://user-images.githubusercontent.com/42181953/135710584-b4cfa823-cb5a-42f6-a6b9-86c50b5506cf.png)
just include the GitHub icon on socials and add this repo link to it

**Comment by harshitsuthar77731** [comment]
i can do it for you

**Comment by wasim7raja10** [comment]
> i can do it for you

@harshitsuthar77731 ok. But don't do it for me, do it for yourself. 🙂

**Comment by harshitsuthar77731** [comment]
i have good experience of creating website and all i want to contribute

**Comment by wasim7raja10** [comment]
@harshitsuthar77731 go for it. I'm assigning it to you.

**Comment by harshitsuthar77731** [comment]
thank you so much

**Comment by wasim7raja10** [comment]
@harshitsuthar77731 you may look at other issues that are open in this repository if you have prior development experience.

**Comment by harshitsuthar77731** [comment]
yes i would like to collobrate

**Comment by preeti-14-7** [comment]
assign this issue to me. I would like to work on this.
