### ISSUE TITLE
Add title bar in pie chart

### ISSUE THREAD

**Issue by OfficialSaurabh** [wasim7raja10/Codeforces-tracker#21]
- Add title bar with the title in a pie chart
- Change the position of labels from left to right
- Both pie chart cards will align between the width of the heatmap

 Now

![Screenshot (5)](https://user-images.githubusercontent.com/31384539/135763921-01f2f797-ba70-426a-b5f2-875f3bc46e06.png)

After completing card will look like this with the title and labels will be in the right side

![Screenshot (6)](https://user-images.githubusercontent.com/31384539/135763953-5307b353-d8cb-4b0e-bb38-776e1d6ed663.png)

**Comment by Harshavardhan7678** [comment]
Hey @OfficialSaurabh, I would like to try this.

**Comment by OfficialSaurabh** [comment]
> Hey @OfficialSaurabh, I would like to try this.

@Harshavardhan7678 you are assigned
