### ISSUE TITLE
Add Pie chart in the side.nav

### ISSUE THREAD

**Issue by wasim7raja10** [wasim7raja10/Codeforces-tracker#6]
![Screenshot from 2021-10-02 12-35-08](https://user-images.githubusercontent.com/42181953/135707113-1418cf09-9594-4005-af68-439c126a0038.png)

1. Use bootstrap appropriate components if necessary to make it responsive.
2. Use appropriate HTML tags and attributes if required so that the data can be updated.
3. Use Google chart for the pie chart (read [CONTRIBUTING.md](https://github.com/wasim7raja10/Codeforces-tracker/blob/main/CONTRIBUTING.md) )
4. refer to [drive](https://drive.google.com/file/d/1UtiWpcFj6Ij_147YWT3duR8FXmY85VYY/view?usp=drivesdk) for the whole UI

**Comment by JigmeT123** [comment]
Please assign me with this issue. Do let me know if you have deadline for this ?

**Comment by wasim7raja10** [comment]
> Please assign me with this issue. Do let me know if you have a deadline for this ?

@JigmeT123 there is a soft deadline of tomorrow. I have assigned it to you.

**Comment by JigmeT123** [comment]
Just completed. Review [PR](https://github.com/wasim7raja10/Codeforces-tracker/pull/18)

**Comment by wasim7raja10** [comment]
> Just completed. Review [PR](https://github.com/wasim7raja10/Codeforces-tracker/pull/18)
> 

Awesome. I will check it out in a hour or two.

**Comment by wasim7raja10** [comment]
> Just completed. Review [PR](https://github.com/wasim7raja10/Codeforces-tracker/pull/18)
> 

Hey @JigmeT123 It looks great. Don't make a separate html for it. It should be in sidenav.html file. 
And test it on phone screen size, the horizontal scroll is not expected. Please make it responsive.

**Comment by JigmeT123** [comment]
> > Just completed. Review [PR](https://github.com/wasim7raja10/Codeforces-tracker/pull/18)
> 
> Hey @JigmeT123 It looks great. Don't make a separate html file for it. It should be in sidenav.html file. And test it on phone screen size, the horizontal scroll is not expected. Please make it responsive.

Sure will fix that.
