### ISSUE TITLE
add bubble chart card in sidenav.html

### ISSUE THREAD

**Issue by wasim7raja10** [wasim7raja10/Codeforces-tracker#7]
![Screenshot from 2021-10-02 13-31-38](https://user-images.githubusercontent.com/42181953/135708643-e760556f-f8b6-4526-836c-a85fa1c9c6ba.png)

1. Size of the card should be flexible with the size of the bubble.
2. The card should be responsive so that it looks nice on mobile. (add horizontal scroll for mobile)
3. The chart should be readable on mobile if there are lots of data.
4. label color and text should match with the bubble color and text.

refer *UI of the web app* -> [drive](https://drive.google.com/file/d/1UtiWpcFj6Ij_147YWT3duR8FXmY85VYY/view?usp=drivesdk) for the complete layout

**Comment by nishantkumar1308** [comment]
assign it to me i can do it.

**Comment by wasim7raja10** [comment]
> assign it to me i can do it.

You are assigned. If you have any doubt, tell us. @nishantkumar1308 please follow the appropriate git workflow. Refer to the link given in readme.

**Comment by nishantkumar1308** [comment]
@wasim7raja10 I only have to create bubble chart ?

**Comment by wasim7raja10** [comment]
> @wasim7raja10 I only have to create bubble chart ?

@nishantkumar1308 yes. And design it like shown in the picture. Also you can refer to the link for the complete UI.

**Comment by nishantkumar1308** [comment]
Thanks @wasim7raja10  I am working on it.

**Comment by nishantkumar1308** [comment]
bubble chart added #22
Please check it and kindly give me hactoberfest-accepted tag on my pr.

**Comment by wasim7raja10** [comment]
> bubble chart added #22
> Please check it and kindly give me hactoberfest-accepted tag on my pr.

I will test it in a moment.

**Comment by nishantkumar1308** [comment]
I try my best to make it as good as possible . I am a beginner in Open source.
If there any issue tell me i will try to resolve it.

**Comment by nishantkumar1308** [comment]
can i use d3.js to create bubbles?

**Comment by wasim7raja10** [comment]
> can i use d3.js to create bubbles?

Yes, why not !

**Comment by nishantkumar1308** [comment]
Ok Thanks!!!
