### ISSUE TITLE
Fix hover effect on the link of sidenav

### ISSUE THREAD

**Issue by wasim7raja10** [wasim7raja10/Codeforces-tracker#9]
![image](https://user-images.githubusercontent.com/42181953/135709315-760ca6d2-a5e0-4d66-bfd7-fa1232cbafca.png)

While hovering on the link of the side-nav, the icon is not affected while it is expected to show effect.  Fix this bug.

**Comment by B1TSH3LL** [comment]
I Can Do It For You. Can You Please Describe Bit More What You Want To Fix On Hover ???

**Comment by wasim7raja10** [comment]
> I Can Do It For You. Can You Please Describe Bit More What You Want To Fix On Hover ???

@B1TSH3LL So if you link on any link on the sidenav (say Profile) the icon is not highlighted. So you can fix it so that the both the link and icon adjacent to it get highlighted while hovering.

**Comment by B1TSH3LL** [comment]
Yupp I Can Work On It. I Would Love To DO.

**Comment by wasim7raja10** [comment]
> Yupp I Can Work On It. I Would Love To DO.  Can You Please Assign It To Me ?

@B1TSH3LL sure.

**Comment by B1TSH3LL** [comment]
can i create PR in new Master branch or same main ????

**Comment by wasim7raja10** [comment]
> can i create PR in new Master branch or same main ????
> 

@B1TSH3LL create PR in main branch

**Comment by wasim7raja10** [comment]
> can i create PR in new Master branch or same main ????
> 

@B1TSH3LL create PR in main branch
